[project]
name = "fastapi-basic"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.128.5",
    "pydantic>=2.12.5",
    "scalar-fastapi>=1.6.1",
    "uvicorn>=0.40.0",
]
